version: "2"
name: "Auth Backend"
services:
  db:
    image: postgres:15
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: mySecretKey
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    # restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  grafana:
    image: grafana/grafana-oss
    # restart: always
    ports:
      - "3000:3000"

  prom-server:
    image: prom/prometheus
    # restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  db_data:
  redis_data: